### ISSUE TITLE
US 01.01.01 Add QR Codes to Account for Increased Scores

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#25]
As a player, I want the ability to add new QR codes to my account, so that I can earn more points and increase my overall score in the QR Code Hunt Game.

Priority: High
Story Point: 4
Risk: Medium

**Comment by ghost** [comment]
Acceptance Criteria:

1.  The player should be able to use "Add QR Code" feature on the home page after they have successfully to register an account.
2. The player press the "Add QR Code" feature on the home page should automatically trigger their device's camera.
3. ALL QR code must be verified for validity and authenticity before added into player's account.
4. The system should notify the player if the QR is successfully added to the account
5. The player score should be updated every time if there is a new QR code is added.
6. The player should be access the their QR code list in the my account page to view all the QR code that they had scanned.
7. The player can me multiple QR code to their account.
8. if player is online their score should be automatically upload to the region and country leaderboard, they will allow players to compete with each others

Priority: High

**Comment by NorthstarWang** [comment]
Implementation:
When user take photo and input relevant info, it will be store to database using DatabaseController and add score
