### ISSUE TITLE
US 01.02.01 Viewing QR Codes in the Player's Account

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#29]
As a player, I want to be able to see what QR codes I have added to my account so that I do not accidentally add the same QR code again.

Priority: Medium
Story Point: 3
Risk Level: Medium

**Comment by ghost** [comment]
Acceptance Criteria:

1. player will have a feature to keep track of all QR code they have scan.
2. the system will also have an feature automatically help players to eliminate duplicate QR code in their account. 
3. player scanned an QR code more than once the system will alert the player that the "QR code has been scanned Try different one "

Priority: Medium

**Comment by NorthstarWang** [comment]
Duplicate feature with #34
