### ISSUE TITLE
US 01.04.01 View QR Code Scores

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#32]
As a player, I want to see my highest and lowest scoring QR codes, so that I can know the range of my QR Code Score and compete with other players for the highest-scoring QR code.

Priority: High
Story Point: 3
Risk Level: Medium

**Comment by ghost** [comment]
Acceptance Criteria:

1. Every QR code have a score when a player is scanned the system will place the QR code in the correct spot in the list and displace the score.
2.  The system will also calculate the total score of all QR code and allow player to review it .
3. The player can compete with each other who has scanned the highest QR score or compete who has total highest score.
4. System don't allow same QR code appear in the QR code list it will automatically delete duplicate.
5. players should be able to review other player highest score QR score they have scanned in their own device's

Priority: High
Story Point: 3
Risk Level: Medium

**Comment by NorthstarWang** [comment]
Implementation:
Complete this code with #34 , a sorting functionality to the list
