### ISSUE TITLE
US 02.01.01 Record Information for QR Codes

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#36]
As a player, I want to be able to scan QR codes and record a photo of the location or object, and the geolocation of the location or object, so that I can describe the QR codes that I have and record the story or moment I find it. 

Priority: High
Story Point: 5
Risk Level: High

**Comment by ghost** [comment]
Acceptance Criteria:

1. The player logs into the game on their device.
2. The player uses the QR code scanning feature of the game to scan QR codes at different locations.
3. After scanning a QR code, the player is given the option to take a photo of the location or object associated with the code.
4. The app automatically records the geolocation of the player's device at the time of the scan.
5. The player can view a list of all the QR codes they have scanned, along with the associated photo, location, and date/time of the scan.
6. The player can add notes or descriptions to each QR code scan, such as a brief story or reflection on their experience.
7. The player can use this information to remember their experiences and share them with others.

Priority: High
Story Point: 5
Risk Level: High

**Comment by NorthstarWang** [comment]
Implementation:
By clicking the camera button at MainActivity, the user should enter the camera and take down the photo of the code, it will prompt for the user's preferences regarding the code. This feature is related to US 02.02.01(#37) and US 02.05.01(#41)
