### ISSUE TITLE
US 02.02.01 Comment On QR Codes

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#37]
As a player, I want to be able to comment on QR codes, so that I can describe the QR codes that I have.

Priority: High
Story Point: 4
Risk Level: Medium

**Comment by ghost** [comment]
Acceptance Criteria:

1. The player logs into the game on their device.
2. The player uses the QR code scanning feature of the game to scan QR codes at different locations.
3. After scanning a QR code, the player is given the option to leave a comment on the code.
4. The player can write a short description of their experience, thoughts, or observations about the QR code.
5. The player can view a list of all the QR codes they have scanned, along with the associated comments.
6. Other players can view the comments left by the player and respond to them if desired.
7. The player can use the comments to share their experiences with others and see what others have to say about the same QR codes.

Priority: High
Story Point: 4
Risk Level: Medium

**Comment by NorthstarWang** [comment]
Implementation:
When users take photo of code, a dialog would prompt for his optional comment on the code
