### ISSUE TITLE
US 02.03.01 Browse QR Codes

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#38]
As a player, I want to be able to browse QR codes that I own, so that I would see what I scanned and not add them again.

Priority: Medium
Story Point: 3
Risk Level: Low

**Comment by ghost** [comment]
Acceptance Criteria:

1. The player logs into the game on their device.
2. The player uses the QR code scanning feature of the game to scan QR codes at different locations.
3. Each time the player scans a QR code, the app records this information and adds it to a list of QR codes the player has scanned.
4. The player can view the list of QR codes they have scanned by accessing a dedicated page or menu within the game.
5. The list of QR codes can be sorted and filtered in various ways to make it easy for the player to find what they're looking for.
6. The player can see the date and location of each scan, along with any associated comments or photos.
7. The player can use the list of QR codes to see what they have found and to avoid scanning the same codes again.

Priority: Medium
Story Point: 3
Risk Level: Low

**Comment by NorthstarWang** [comment]
Duplicate feature with #34
