### ISSUE TITLE
US 02.05.01 QR Code with a Unique Human Readable Name

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#41]
As a player, I want QR codes to have a unique human readable name, so that I can mention it very quickly.

Priority: Low
Story Point: 1
Risk Level: Low

**Comment by ghost** [comment]
Acceptance Criteria:

1. The player logs into the game on their device.
2. The player scans a QR code using the game's QR code scanning feature.
3. After scanning the QR code, the game assigns a unique, easily-readable name to the code.
4. The name is based on the location or object associated with the QR code and is designed to be memorable and easy to read.
5. The player can see the unique name for each QR code they scan in their list of scanned codes.
6. The player can also see the unique name for each QR code in lists of codes scanned by other players.
7. The player can use the unique names of QR codes to quickly reference and discuss specific codes with other players, without having to use long, complex QR code strings.
8. The player can also use the unique names to more easily remember which codes they have scanned and where they were located.

Priority: Low
Story Point: 1
Risk Level: Low

**Comment by NorthstarWang** [comment]
Implementation:
When users take photo of code, a dialog would prompt for his optional name on the code, else the code will be left as format of "{point}_{type}_{date}"
