### ISSUE TITLE
US 02.06.01  QR Code Visual Representation

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#42]
As a player, I want to see a visual representation of a QR code relatively unique to that QR code, so that it provides a way for the player to visually identify a QR code.

Priority: Low
Story Point: 2
Risk Level: Low

**Comment by ghost** [comment]
Acceptance Criteria:

1. The player logs into the game on their device.
2. The player scans a QR code using the game's QR code scanning feature.
3. After scanning the QR code, the game creates a unique, easily-identifiable visual representation for the code.
4. The visual representation is based on the location or object associated with the QR code and is designed to be easily recognizable and distinctive.
5. The player can see the unique visual representation for each QR code they scan in their list of scanned codes.
6. The player can also see the unique visual representation for each QR code in lists of codes scanned by other players.
7. The player can use the unique visual representations of QR codes to quickly recognize a code when they see it and associate it with the location or object it represents.
8. The player can also use the unique visual representations to more easily remember which codes they have scanned and what they represent.

Priority: Low
Story Point: 2
Risk Level: Low

**Comment by NorthstarWang** [comment]
Implementation:
When user open the code list, TotalScannedCodeActivity, user should not see thumbnail of code image itself, but a number image with different color indicating the score of the code. Complete US 01.06.01(#34) prior to this issue
