### ISSUE TITLE
US 03.02.01 Remember Me

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#44]
As a player, I do not want to log into my application using a username and password as my device can identify me, so that I can access the application easier.

Priority: Medium
Story Point: 3
Risk Level: High

**Comment by ghost** [comment]
Acceptance Criteria:

1. The player launches the game on their device.
2. The game uses device identification to recognize the player, eliminating the need for a username and password.
3. The player's device provides the game with the necessary information to log the player in.
4. The player is automatically logged into the game and taken directly to their profile.
5. The player's profile displays their username, contact information, and game statistics such as the total number of QR codes scanned and the total score.
6. The player can begin playing the game and scanning QR codes without the need to enter a username and password.
7. The use of device identification eliminates the need for the player to remember and enter login information, making it easier and faster for the player to access the game.

Priority: Medium
Story Point: 3
Risk Level: High

**Comment by NorthstarWang** [comment]
Unnecessary feature:
Using google auth, the application will always auto-login
