### ISSUE TITLE
US 08.01.01 NO Big Image Online

### ISSUE THREAD

**Issue by WenxinLi311** [NorthstarWang/SoloCarry#54]
As an owner, I don’t want to store big images online, so that I can save storage space and save cost.

Priority: Medium
Story Point: 4
Risk Level: Medium

**Comment by ghost** [comment]
Acceptance Criteria:

1. Efficient image compression and storage system
2. Ability to store images at a lower resolution or file size, while still preserving quality and legibility
3. Automated removal of outdated or unused images
4. Monitoring of storage usage and costs
5. Ability to make informed decisions about optimizing storage space and minimizing costs
6. Cost-effective and efficient storage solution that provides a high-quality user experience for players.

Priority: Medium
Story Point: 4
Risk Level: Medium
